version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    image: celery:latest
    environment:
      CELERY_BROKER: redis://redis:6379
    depends_on:
      - redis:

