version: "3.9"

services:
  oracle:
    image: oracle/database:enterprise-edition-latest
    environment:
      ORACLE_SID: orcl
      ORACLE_PWD: my_password
    ports:
      - "1521:1521"
    volumes:
      - ./oracle-data:/u01/app/oracle/oradata