version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak_db
        POSTGRES_USER: keycloak_db
        POSTGRES_PASSWORD: password_db
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak_db
        DB_USER: keycloak_db
        DB_SCHEMA: public
        DB_PASSWORD: password_db
        KEYCLOAK_USER: user_name
        KEYCLOAK_PASSWORD: password
      ports:
        - 9080:8080
      depends_on:
        - postgres

