version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: "grafana-simple-json-datasource"
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
