version: "3.9"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_user
      MONGO_INITDB_ROOT_PASSWORD: my_password
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db