version: "3.9"

services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: my_user
      WORDPRESS_DB_PASSWORD: my_password
      WORDPRESS_DB_NAME: my_database
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"