version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql