version: "3.9"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
